// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3cbklGmjKw-Ciewm5FymxJm3MpE_G8I',
    appId: '1:748299435231:web:9b24fa29393a4e81c83d6a',
    messagingSenderId: '748299435231',
    projectId: 'hostel-management-85321',
    authDomain: 'hostel-management-85321.firebaseapp.com',
    storageBucket: 'hostel-management-85321.appspot.com',
    measurementId: 'G-LV54QEKQM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQ960vZj8XFaMIh4F5cqt_PuDvWsfRVI',
    appId: '1:748299435231:android:dcc4725766e1969ac83d6a',
    messagingSenderId: '748299435231',
    projectId: 'hostel-management-85321',
    storageBucket: 'hostel-management-85321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyECr3H9UCexpgAjeS1Pyl5C5U0yE0Hmg',
    appId: '1:748299435231:ios:edcb91f6fd122280c83d6a',
    messagingSenderId: '748299435231',
    projectId: 'hostel-management-85321',
    storageBucket: 'hostel-management-85321.appspot.com',
    iosBundleId: 'com.example.hostelManagementUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyECr3H9UCexpgAjeS1Pyl5C5U0yE0Hmg',
    appId: '1:748299435231:ios:cced2362f72d7d51c83d6a',
    messagingSenderId: '748299435231',
    projectId: 'hostel-management-85321',
    storageBucket: 'hostel-management-85321.appspot.com',
    iosBundleId: 'com.example.hostelManagementUser.RunnerTests',
  );
}
